version: '2'
services:
  web:
    build: ./
    depends_on:
      - "db"
    ports:
      - "8000:80"
    expose:
      - "80"
    volumes:
      - ./unipet:/var/www/html/
    links:
      - db:db_container
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: unipet